### PR TITLE
Integrated Accessibility Features

### PR DESCRIPTION
**Pull request by tnbnicer**
New features may be enabled optionally. Below is a description of features added.

=====================================================

Navigable Tabindexes.

##Keystrokes (when enabled)

cycle to next tab [Tab]
cycle to previous tab [Shift + Tab]
pause/play [Enter or Spacebar]
fast-forward [Right Arrow]
rewind [Left Arrow]
show/hide volume slider [Enter or Spacebar]
volume increase [Up Arrow]
volume decrease [Down Arrow]
download [Enter]

selector: .player-with-accessibility (see ../examples/multiple-instance.html - player 4)
init option: .enableKeystrokes

Tested on Chrome, Firefox, Edge (latest versions) and IE 11. HMTL5 standards compliant (afaik).

Compatible with several players simultaneously.
(see ../examples/multiple-instances.html - players 3 and 4)

##Functions

showVolume()
showhideVolume()
setCurrentTime(time)
setVolume(volume)
pressKb(event)

##Changes

JS

html (static) template: div element with '.holder' style (stabilizes spinner icon)
html (static) template: interactive aria attributes
html (static) template: accessibility text
iOS and Android detection: 'isDevice' variable
time format: 00:00
volume: more responsive, i.e. smaller increments
volume: default volume set to 0.81 (best practice)
using style 'visibility' property instead of 'display' property in 'showLoadingIndicator()' function and 'hideLoadingIndicator()'.

CSS

class: .holder
dotted outline style on hover and focus
hidden style for accessibility text

##Transpiled Version

../src/scss/main.scss >>> ../dist/css/green-audio-player.css
../src/scss/main.scss >>> ../dist/css/green-audio-player.min.css

../src/js/main.js >>> ../dist/js/green-audio-player.js
../src/js/main.js >>> ../dist/js/green-audio-player.min.js

=====================================================

Hi @greghub
Are you ready for version 1.0.15?

### CODE REVIEW

**Comment by greghub** [comment]
@tnbnicer Thank you very much for the amazing work you've done on the Green Audio Player! This is a major and very important contribution, which made this library so much better. Thank you!

**Comment by tnbnicer** [comment]
@greghub 

Thank you for accepting my pull request. :)

An amazing player!

I have been giving some thought to a few more tweaks.

**Error handling of autoplay**
- Autoplay should return a Promise, since not all browsers support automatic playback.

**Prevent errors for `preload = 'none'`** (seldom used audio attribute)
- if used, seek and play should be disabled before the source loads, and reenabled when loaded.

**Title attribute to complement `aria-label`** (not necessary but possible)
- for play, volume and download buttons. (visible on focus)

**Pause while seeking with keyboard**
- playback temporarily paused. (already paused for manual seeking via mouse/touch)

Would it be all right to do a pull request? I'm in the process of updating my fork.  Maybe you can still merge the changes into 1.10?

**Comment by greghub** [comment]
Thank you, I’ll be glad to, these would be very important updates! That could be version 1.1.1

**Comment by tnbnicer** [comment]
I requested the new pull. Some features might some more testing on various devices, but in theory everything works.

**Pull request merged**
